version: '3.7'
services:
#   # MQTT Broker (Eclipse Mosquitto)
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto_lidar
    user: "${UID}:${GID}"  # Run as the current user from the host
    ports:
      - "1883:1883"   # Expose MQTT broker
      # - "9001:9001"   # WebSocket (optional, if you need it)
    volumes:
      - "./mosquitto/config:/mosquitto/config/"
      - "./mosquitto/logs:/mosquitto/logs"
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"
    # If you don't have a custom mosquitto.conf,
    # you can remove the volumes section. Or place a minimal config if needed.
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
    - lidar-network

  app:
    build: .
    container_name: lidar-visualizer
    user: "${UID}:${GID}"  # Run as the current user from the host
    ports:
      - "${APP_PORT:-8000}:8000"
    environment:
      - MQTT_BROKER_HOST=${MQTT_BROKER_HOST:-localhost}
      - MQTT_BROKER_PORT=${MQTT_BROKER_PORT:-1883}
      - MQTT_TOPIC=${MQTT_TOPIC:-/esp32/lidar/distance}
    restart: unless-stopped
    volumes:
      - ./:/app
    networks:
      - lidar-network
    depends_on:
      - mosquitto

networks:
  lidar-network:
    driver: bridge

